"Location: ~/.vimrc (rename to dotfile, but want it visible in GitHub)
"default settings
syntax on 

set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set colorcolumn=80,120

"plugins
call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'

call plug#end()

"apply colorscheme
colorscheme gruvbox
set background=dark

