# vim key bindings
set-window-option -g mode-keys vi

# proper colors
set -g default-terminal xterm-256color

# turn mouse scrolling on
set-option -g mouse on

# cut and paste with vim keybindings
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
set -s set-clipboard external

# long history
set -g history-limit 10000

# start horizontal/vertical panes in the same window on the current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
# bind c new-window -c "#{pane_current_path}" # don't do this for new window

# tmux plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
